### ISSUE TITLE
`auditgui` + `webgui` enabled and social disabled breaks compose file generation

### ISSUE THREAD

**Issue by jaredmcgrath** [pacefactory/deployment-scripts#25]
Attempted to run update script, reconfigured with `auditgui` + `webgui` enabled and social profile disabled.
This will error out, generating an empty compose file.

Specific error:
```
Building docker-compose.yml...

docker compose --project-name deployment-scripts --env-file .env --profile audit --profile base --profile offline -f compose/docker-compose.audit.yml -f compose/docker-compose.base.yml -f compose/docker-compose.offline.yml convert
service "social_web_app" has neither an image nor a build context specified: invalid compose project
```

Full log of command attached
[update.log](https://github.com/pacefactory/deployment-scripts/files/11093116/update.log)

**Comment by jkingry** [comment]
Need to handle the `nosocial` case

- For all cases, scv2_webgui will be hosted at `/scv2`
- no social, no audit `/` -> `/scv2`
- no social, + audit, `/` `/scv3`
- social -> `/` -> `social app`
